{
 "title": "Threat Hunting API - Service Overview",
 "tags": [
  "observability",
  "sre"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "path",
    "query": {
     "query": "label_values(http_requests_total, path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ROW 1: User Experience (Golden Signals)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Throughput (RPS by Status)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{path=~\"$path\"}[1m])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Latency Breakout (p50/p95/p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{path=~\"$path\"}[2m])) by (le))",
     "legendFormat": "p50 (Median)"
    }
   ]
  },
  {
   "title": "Global Error Rate (5xx)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~\"5..\", path=~\"$path\"}[1m])) or vector(0)) / sum(rate(http_requests_total{path=~\"$path\"}[1m])) * 100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "ROW 2: Saturation & Resources (Root Cause)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }
  },
  {
   "title": "DB Pool Saturation (Limit: 20)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "db_pool_checked_out_connections",
     "legendFormat": "Checked Out (Busy)"
    }
   ]
  },
  {
   "title": "API CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "Process CPU"
    }
   ]
  }
 ]
}